### PR TITLE
954 ubsan tinystring

### LINKED ISSUE #954: UBSan flagging TinyString
I ran the unit tests with the available sanitizer options, and undefined behavior sanitizer flagged tinyString. 
Snippet:
```
../test/../src/writer/tinyString.h:69:58: runtime error: null pointer passed as argument 1, which is declared to never be null
```

UBSan is complaining about `std::memcmp` being called with one of the arguments being `nullptr`. `min_size == 0` should be sufficient given the implementations of `std::memcmp` I saw in libstdc++ and libc++, but in the interest of being thorough, I'll add a couple of checks to make UBSan happy.

For reference, `b_sanitize=undefined` in the `default_options` in `meson.build` will enable UBSan.

### PR DESCRIPTION
**Pull request by ThisIsFineTM**
Making undefined behavior sanitizer happy with tinyString.h

Closes #954

### CODE REVIEW

File: meson.build [hunk 1]
```diff
@@ -1,7 +1,7 @@
 project('libzim', ['c', 'cpp'],
   version : '9.2.3',
   license : 'GPL2',
-  default_options : ['c_std=c11', 'cpp_std=c++17', 'werror=true'])
+  default_options : ['c_std=c11', 'cpp_std=c++17', 'werror=true', 'b_sanitize=undefined'])
```
[the remark this answers is not in the document]
Comment (ThisIsFineTM) [reply meson.build]: I agree. I just had it in the PR by default so each logical step could be verified and reproduced for purposes of review. I can squash those changes out.

File: src/writer/tinyString.h [hunk 2]
```diff
@@ -66,13 +66,19 @@ namespace zim
...
-          auto ret = std::memcmp(m_data, other.m_data, min_size);
+          const bool this_lt_other = (m_size < other.m_size);
+          const auto min_size = std::min(m_size, other.m_size);
+          if(min_size == 0) {
+              return this_lt_other;
+          }
+          const auto ret = std::memcmp(m_data, other.m_data, min_size);
           if (ret == 0) {
-            return m_size < other.m_size;
+            return this_lt_other;
```
[the remark this answers is not in the document]
Comment (ThisIsFineTM) [reply src/writer/tinyString.h:81]: I agree. Would you like that utility wrapper to be put locally in the header file or do you think it would be more appropriate to put it in its own header in the src file tree? I'm personally leaning towards putting it in its own header since memcmp is also used in `src/fileimpl.cpp` and some tests. Propagating that would preempt potential further UBSan complaints. I can propagate that utility function in this PR or I can put it in a separate PR. Whichever you think is best.

[the remark this answers is not in the document]
Comment (veloman-yunkan) [reply src/writer/tinyString.h:81]: Please put `safe_memcp()` in `src/tools.h`. But there is no need to replace `std::memcp()` just in case. We should do it only in contexts where it may be passed a `nullptr` argument.

[the remark this answers is not in the document]
Comment (ThisIsFineTM) [reply src/writer/tinyString.h]: Done. Commits are squashed and rebased onto the latest main at time of writing. I just made `safe_memcmp` a template so the compiler will complain if you're using memcmp on pointers to disparate types.

**Review by veloman-yunkan — APPROVED** [review]

**Comment by kelson42** [comment]
I can not merge it as CI does not pass

**Comment by ThisIsFineTM** [comment]
Putting the error messages here to consolidate information. I'll spin up local containers to test this and add it to my local testing procedure while I investigate / put in a fix. I just find it strange that it works on apple arm, doesn't work on regular arm, works on local fedora (gcc and clang), works on focal(22.04LTS)/jammy(20.04LTS) ubuntu, but doesn't work on ubuntu noble(24.04). Spending some time on this and if I can't figure it out I'll take out the template / noexecpt version for the simpler one so we can move on.

Packages / build-deb (ubuntu-noble)
```
FAILED: test/tinyString.p/tinyString.cpp.o 
c++ -Itest/tinyString.p -Iinclude -I../include -Isrc -I../src -fdiagnostics-color=always -Wall -Winvalid-pch -Werror -std=c++17 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DLIBZIM_EXPORT_PRIVATE_DLL -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/github/workspace=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection '-fdebug-prefix-map=/github/workspace=/usr/src/libzim-9.2.3+git202502150353.094edb0~noble' -Wdate-time -D_FORTIFY_SOURCE=3 -DGTEST_HAS_PTHREAD=1 -pthread -DWITH_TEST_DATA=0 -MD -MQ test/tinyString.p/tinyString.cpp.o -MF test/tinyString.p/tinyString.cpp.o.d -o test/tinyString.p/tinyString.cpp.o -c ../test/tinyString.cpp
In file included from ../test/../src/writer/tinyString.h:23,
                 from ../test/tinyString.cpp:22:
In function ‘zim::safe_memcmp<char>(char const*, char const*, unsigned long)int’,
    inlined from ‘zim::writer::TinyString::operator<(zim::writer::TinyString const&) const’ at ../test/../src/writer/tinyString.h:74:39,
    inlined from ‘(anonymous namespace)::TinyStringTest_chars_Test::TestBody()’ at ../test/tinyString.cpp:65:3:
../test/../src/writer/../tools.h:83:46: error: ‘memcmp’ specified bound [1, 65534] exceeds source size 0 [-Werror=stringop-overread]
   83 |       return (count == 0UL) ? 0 : std::memcmp(lhs, rhs, count);
      |                                   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In function ‘zim::safe_memcmp<char>(char const*, char const*, unsigned long)int’,
    inlined from ‘zim::writer::TinyString::operator<(zim::writer::TinyString const&) const’ at ../test/../src/writer/tinyString.h:74:39,
    inlined from ‘(anonymous namespace)::TinyStringTest_chars_Test::TestBody()’ at ../test/tinyString.cpp:70:3:
../test/../src/writer/../tools.h:83:46: error: ‘memcmp’ specified bound [1, 65534] exceeds source size 0 [-Werror=stringop-overread]
   83 |       return (count == 0UL) ? 0 : std::memcmp(lhs, rhs, count);
      |                                   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Linux (linux-aarch64-dyn, true)
Linux (linux-aarch64-dyn, false)
```
 /home/runner/BUILD_neutral/TOOLCHAINS/aarch64/bin/aarch64-linux-gnu-g++ -Isrc/libzim.so.9.2.3.p -Isrc -I../src -Iinclude -I../include -Istatic -I/home/runner/BUILD_aarch64-linux-gnu/INSTALL/include -fdiagnostics-color=always -Wall -Winvalid-pch -Werror -std=c++17 -O0 -g -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DLIBZIM_EXPORT_PRIVATE_DLL -fPIC -pthread -MD -MQ src/libzim.so.9.2.3.p/archive.cpp.o -MF src/libzim.so.9.2.3.p/archive.cpp.o.d -o src/libzim.so.9.2.3.p/archive.cpp.o -c ../src/archive.cpp
In file included from ../src/archive.cpp:29:0:
../src/tools.h:81:78: error: ‘nodiscard’ attribute directive ignored [-Werror=attributes]
   int safe_memcmp(T const *const lhs, T const *const rhs, std::size_t count) noexcept
                                                                              ^~~~~~~~
```

**Comment by ThisIsFineTM** [comment]
@kelson42 I applied fixes but was unable to reproduce the errors locally. I need to spend some time fighting SELinux on my system. Would you mind kicking off another CI run to see if those fixes worked? Thanks.
