### ISSUE TITLE
libzim-resources.h: No such file or directory

### ISSUE THREAD

**Issue by probonopd** [openzim/libzim#212]
Cannot build on Ubuntu 14.04, `libzim-resources.h: No such file or directory`:

```
10.47s$ ninja -C build
ninja: Entering directory `build'
[24/47] Compiling C++ object 'src/zim@sha/writer_xapianIndexer.cpp.o'.
FAILED: src/zim@sha/writer_xapianIndexer.cpp.o 
g++  -Isrc/zim@sha -Isrc -I../src -Iinclude -I../include -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++11 -O0 -g -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -fPIC -pthread -MMD -MQ 'src/zim@sha/writer_xapianIndexer.cpp.o' -MF 'src/zim@sha/writer_xapianIndexer.cpp.o.d' -o 'src/zim@sha/writer_xapianIndexer.cpp.o' -c ../src/writer/xapianIndexer.cpp
../src/writer/xapianIndexer.cpp:21:30: fatal error: libzim-resources.h: No such file or directory
 #include "libzim-resources.h"
                              ^
compilation terminated.
[26/47] Compiling C++ object 'src/zim@sha/writer_zimcreator.cpp.o'.
ninja: build stopped: subcommand failed.
The command "ninja -C build" exited with 1.
```

My build script:
https://github.com/probonopd/kiwix-desktop/blob/52e7b9d85727b6458ee1549e935ddaaa7b5efa57/.travis.yml
Full build log:
https://api.travis-ci.com/v3/job/187282267/log.txt

**Comment by kelson42** [comment]
@probonopd Which version of the libzim do you try to compile?

**Comment by probonopd** [comment]
`master`:

https://github.com/probonopd/kiwix-desktop/blob/52e7b9d85727b6458ee1549e935ddaaa7b5efa57/.travis.yml#L34-L40

**Comment by kelson42** [comment]
What are your versions of both `meson` and `ninja`?

**Comment by probonopd** [comment]
meson 0.44.1 (the last one that runs on Ubuntu trusty)

https://github.com/probonopd/kiwix-desktop/blob/52e7b9d85727b6458ee1549e935ddaaa7b5efa57/.travis.yml#L24

ninja master

https://github.com/probonopd/kiwix-desktop/blob/52e7b9d85727b6458ee1549e935ddaaa7b5efa57/.travis.yml#L27

**Comment by kelson42** [comment]
@mgautierfr Could you please have a look to this? @probonopd seems to do things correctly.

**Comment by fr0zenrain** [comment]
i have the same issue.does libzim-resources.h is dynamic generate? i can't found this file

**Comment by fr0zenrain** [comment]
release 4.0.6 is ok, do not use master code

**Comment by kelson42** [comment]
@fr0zenrain @probonopd Yes it is generated during the build process. They should be here:
```
$ find . -name "libzim-resources.*"
./build/static/libzim-resources.h
./build/static/libzim-resources.cpp
```

**Comment by probonopd** [comment]
@kelson42 here is my full build log: https://api.travis-ci.com/v3/job/187282267/log.txt - I don''t spot any `libzim-compile-resources` errors, do you?

**Comment by kelson42** [comment]
@probonopd The problem is clear, for some reason the `ninja` cmd does not build the resources. Here it how it looks like by me (Ubuntu 19.04):
```
$ ninja -C build
ninja: Entering directory `build'
[1/51] Generating resources with a custom command.
stopwords/en ['stopwords', 'en']
stopwords/he ['stopwords', 'he']
stopwords/fra ['stopwords', 'fra']
[51/51] Linking target test/template.
```

**Comment by probonopd** [comment]
Can you try on Ubuntu 14.04 (trusty) please?

**Comment by kelson42** [comment]
@probonopd I don't have Ubuntu 14.04 and considering that this Ubuntu is EOL and even not supported anymore, why I should? Any reason to still use this outdated version?

**Comment by kelson42** [comment]
@probonopd Could you upload the `build/compile_commands.json` file please?

**Comment by mgautierfr** [comment]
It may be a issue with the meson version. `0.44.1` is a bit old.
Can you try with `0.49.2` ? (Just run `pip install meson==0.49.2` before running kiwix-build)

**Comment by probonopd** [comment]
I had read somewhere that 0.44.1 is the last one supported on trusty.

**Comment by kelson42** [comment]
@probonopd Have you been able to check with a newer version of `meson`?

**Comment by probonopd** [comment]
Again, I had read somewhere that 0.44.1 is the last one supported on trusty. When I try to install a newer one, I am getting

```
pip3 install meson==0.49.2
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting meson==0.49.2
  Downloading https://files.pythonhosted.org/packages/42/a1/e5b17fe46cd6060edb49f776eecb31c9527a1c3742bbb60630ee439a6e22/meson-0.49.2.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.3MB 14.8MB/s 
    Complete output from command python setup.py egg_info:
    Tried to install with an unsupported version of Python. Meson requires Python 3.5.0 or greater
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-725p6k2b/meson/
The command "pip3 install meson==0.49.2" exited with 1.
```

In general, my experience with meson has been that it is very cumbersome to get it going on all but the most recent systems. Am I missing something?

I am interested in compiling this in a way to allow it to be used on older systems as well.

**Comment by kelson42** [comment]
@probonopd I plan to close that issue soon. Without your feedback, it is complicated to be sure that this is related to an older version of Meson, but this is so far what we believed to happen. If you would confirm, that would allow us to update the README. Unfortunately, we need to move on with Meson most recent/best features. You can still install manually Meson on older system (see our README to know how).

**Comment by probonopd** [comment]
> Without your feedback

What kind of feedback should I give, apart from [what I wrote on April 9](https://github.com/openzim/libzim/issues/212#issuecomment-481112863)?

**Comment by kelson42** [comment]
@probonopd Looks like you need to install a more recent version of Python. Without doing so, and testing with new version of Meson, there is not much more we will do IMO.

**Comment by probonopd** [comment]
it is really cumbersome that this project seems to be accepting dependencies that are newer than what comes with the oldest still-supported LTS distributions. This makes it way harder to compile this for e.g., xenial than need be.

**Comment by kelson42** [comment]
@probonopd First of all, so far this is still only an assumption, that the problem comes from the version of Meson. For the rest I can only agree with you, this is not something I'm really happy with. But we deal here with multiple constraints and some compromises have always to be done. That said, AFAIK Kiwix Desktop Flatpak/Flathub package works fine on older Linux.

**Comment by probonopd** [comment]
Now it starts to compile, but I am running into https://github.com/openzim/libzim/issues/91. Seems like it needs a bleeding edge Xapian as well. Oh well, it would be so nice if it wouldn't require the latest and greatest of everything...

**Comment by probonopd** [comment]
Now running into https://github.com/kiwix/kiwix-lib/issues/6. Looks like it also needs a newer pugixml than what comes with Ubuntu xenial. Oh well, at this point it seems to need a newer version of almost everything. Why can't developers ensure that stuff builds on all still-supported distributions? It's really sad...

**Comment by kelson42** [comment]
The original problem has been explained and answered

**Comment by probonopd** [comment]
Trying to compile this on anything but the newest distributions just feels like running from issue into the next issue... but we will be getting there eventually. Thanks @kelson42 for your help thus far.

**Comment by shoogle** [comment]
As of 25th of April, Ubuntu 14.04 (Trusty) is no longer supported and does not receive updates except for customers paying to be part of Canonical's Extended Security Maintainance (ESM) program. Ubuntu 16.04 (Xenial) is now the oldest supported LTS version of Ubuntu.

https://www.ubuntu.com/about/release-cycle
https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_14.04_LTS_(Trusty_Tahr)

This issue was created before the 25th of April, but not long before. It would be nice if Meson supported distributions right up to EOL but there might have been a good reson for upgrading slightly early.

**Comment by shoogle** [comment]
Interestingly, Meson's [CI tests](https://travis-ci.org/mesonbuild/meson) run on Ubuntu 14.04, so this issue may not have been Meson's fault after all.

**Comment by probonopd** [comment]
I am now using xenial but am still running into compilation issues. Maybe it's not the fault of Meson but I have no clue what to do if Meson fails.

**Comment by JensTimmerman** [comment]
I am running into the same issue on master:

 meson --version
0.54.0

```
ninja-build -C build
ninja: Entering directory `build'
[24/54] Compiling C++ object 'src/25a6634@@zim@sha/writer_xapianIndexer.cpp.o'
FAILED: src/25a6634@@zim@sha/writer_xapianIndexer.cpp.o 
c++ -Isrc/25a6634@@zim@sha -Isrc -I../src -Iinclude -I../include -I/usr/local/include/xapian-1.5/ -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++11 -g -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -fPIC -pthread -MD -MQ 'src/25a6634@@zim@sha/writer_xapianIndexer.cpp.o' -MF 'src/25a6634@@zim@sha/writer_xapianIndexer.cpp.o.d' -o 'src/25a6634@@zim@sha/writer_xapianIndexer.cpp.o' -c ../src/writer/xapianIndexer.cpp
../src/writer/xapianIndexer.cpp:21:30: fatal error: libzim-resources.h: No such file or directory
 #include "libzim-resources.h"

```

manually running the compile-resources script doesn't seem to work
```
./scripts/libzim-compile-resources 
usage: libzim-compile-resources [-h] [--cxxfile CXXFILE] [--hfile HFILE]
                                [--source_dir SOURCE_DIR]
                                resource_file
libzim-compile-resources: error: the following arguments are required: resource_file
```

**Comment by kelson42** [comment]
@JensTimmerman This ticket is old, would you be able please to open a new one and share all details about your setup?

**Comment by JensTimmerman** [comment]
@kelson42 ok, follow up in https://github.com/openzim/libzim/issues/320
