### PR TITLE
Libzim next

### PR DESCRIPTION
**Pull request by mgautierfr**
This is the PR to merge the libzim_next branch into master.

libzim_next has been created with PR already reviewed.

### CODE REVIEW

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
Review of this PR is complicated by the fact that merging of `master` into `libzim_next` and subsequent conflict resolution have been done in one commit. I prefer to perform such non-trivial merges by committing broken code produced by the (failed) automatic merge and then resolving textual and logical conflicts in separate commits. This way the issues encountered during the merge and the way they have been addressed are easier to trace and review.

**Comment by mgautierfr** [comment]
> I prefer to perform such non-trivial merges by committing broken code produced by the (failed) automatic merge and then resolving textual and logical conflicts in separate commits. This way the issues encountered during the merge and the way they have been addressed are easier to trace and review.

With all the conflict git marker inside the code ?
I tend to avoid not compiling code in the git history but in this context it makes sense yes.
Will do the next time :)

> `include/zim/file.(h|cpp)` was reintroduced when merging master into libzim_next

My bad, I checkout them back to port the changes we've made in `File` to `Archive` and I forget to remove them.

---

Last push removes unwanted files, merges again master in libzim_next and fixes conflicts in separated commit.

**Review by veloman-yunkan — APPROVED** [review]
The failure of the Windows build can be fixed separately, no sense delaying this merge because of that.

**Comment by mgautierfr** [comment]
> The failure of the Windows build can be fixed separately, no sense delaying this merge because of that.

We should not :) We add the Windows CI especially to catch compilation errors on Windows. It is not ignore this check the first merge we put the CI in place.

The (3) fixes on Windows are done. And I add a new method since your last review.

**Comment by mgautierfr** [comment]
Last three commits fix few bug I found finalizing the `zim-tools` associated PR.

**Comment by kelson42** [comment]
@mgautierfr Looks like you have merged `master` in your feature branch. Hope this is really what you wanted as both of us don't like this practive.
@veloman-yunkan Would you be able please to review again this PR (latest commits) so we can merge?

File: include/zim/archive.h [hunk 1]
```diff
@@ -313,6 +313,22 @@ namespace zim
...
+       * - On old namespace scheme :
+       *  . All entries are accessible, either using `getEntryByPath` with a specific namespace
+       *    or simply iterating over the entries (with `iter*` methods).
+       *  . Entry's path has namespace included ("A/foo.html")
+       * - On new namespace scheme :
+       *  . Only the "user" entries are accessible with `getEntryByPath` and `iter*` methods.
+       *    To access metadatas, use `getMetadata` method.
+       *  . Entry's path do not contains namespace ("foo.html")
+       */
+      bool useNewNamespaceScheme() const;
```
Comment (veloman-yunkan) [inline include/zim/archive.h:330]: As a query method it better be named `usesNewNamespaceScheme()`

File: src/writer/item.cpp [hunk 2]
```diff
@@ -33,41 +33,67 @@ namespace zim
...
           }
-          return std::make_tuple(true, htmlParser.latitude, htmlParser.longitude);
+#endif
+          return std::make_tuple(false, 0, 0);
         }
 
       private:
+#if defined(ENABLE_XAPIAN)
         zim::MyHtmlParser htmlParser;
+#endif
```
Comment (veloman-yunkan) [inline src/writer/item.cpp]: Though not to be addressed immediately, I want to remind that classes with conditionally compiled data members can lead to mysterious crashes when you compile your code with one set of macros defined and link it with a library built with another set of macros (which breaks the [C++ one definition rule](https://en.wikipedia.org/wiki/One_Definition_Rule)).

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
Just a single naming issue

File: include/zim/archive.h (hunk 1 above)
Comment (mgautierfr) [reply include/zim/archive.h:330]: Hum. You are technically right. But it maybe because I'm not a native English speaker but I'm pretty sure I will miss this `s`.

Maybe we could use the more standard way to query things with `is` or `has` ?

File: src/writer/item.cpp (hunk 2 above)
Comment (mgautierfr) [reply src/writer/item.cpp]: Yes, I totally agree.
This is why I want to rework the "compilation without xapian" part. As I said, libzim now compile without xapian but I'm not sure that it behaves correctly.

The plan is to "simply" remove the whole search/indexing api if libzim is compiled without xapian.
I will also fix this kind of issue in the same time.

File: include/zim/archive.h (hunk 1 above)
Comment (veloman-yunkan) [reply include/zim/archive.h:330]: `hasNewNamespaceScheme()` is fine

**Comment by mgautierfr** [comment]
Last push rename `useNewNamespaceScheme` to `hasNewNamespaceScheme` and squash `fixup!` commits.

**Review by veloman-yunkan — APPROVED** [review]
